# Generated by Django 5.2 on 2025-05-12 21:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0014_alter_group_id_alter_permission_id_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "System Admin"),
                            ("CLUB", "Club Manager"),
                            ("PLAYER", "Player"),
                            ("REFEREE", "Referee"),
                            ("FED_ADMIN", "Federation Admin"),
                            ("PUBLIC", "Public User"),
                            ("COACH", "Coach"),
                            ("EXECUTIVE", "Exco Member"),
                        ],
                        default="PLAYER",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50)),
                ("surname", models.CharField(blank=True, max_length=100)),
                ("user_name", models.CharField(blank=True, max_length=50, unique=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="email address",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("id_number", models.CharField(blank=True, max_length=20)),
                (
                    "id_document_type",
                    models.CharField(
                        choices=[
                            ("BC", "Birth Certificate"),
                            ("PP", "Passport"),
                            ("ID", "National ID"),
                            ("DL", "Driver License"),
                            ("OT", "Other"),
                        ],
                        default="ID",
                        max_length=2,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other"),
                            ("U", "Undisclosed"),
                        ],
                        max_length=1,
                    ),
                ),
                ("club_affiliation", models.CharField(blank=True, max_length=100)),
                ("federation_code", models.CharField(blank=True, max_length=3)),
                ("province_code", models.CharField(blank=True, max_length=3)),
                ("region_code", models.CharField(blank=True, max_length=3)),
                (
                    "fifa_id",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Profile picture (max 2MB)",
                        null=True,
                        upload_to="user_profiles/",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
