# Generated by Django 5.2 on 2025-05-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoverningBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("acronym", models.CharField(max_length=20, unique=True)),
                ("founded_date", models.DateField(blank=True, null=True)),
                ("headquarters", models.CharField(blank=True, max_length=100)),
                ("website", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default="governing_bodies/default_logo.png",
                        upload_to="governing_bodies/logos/",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Governing Bodies",
                "ordering": ["name"],
            },
        ),
    ]
